import { useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";

import Screen from "../../components/layout/Screen.jsx";
import Button from "../../components/common/Button.jsx";
import ErrorBanner from "../../components/common/ErrorBanner.jsx";
import Loading from "../../components/common/Loading.jsx";

import {
  refineDescription,
  createServiceRequest,
} from "../../api/services.js";

import { getOnboarding } from "../../lib/preferences.js";


export default function ReviewRequest() {
  const navigate = useNavigate();
  const location = useLocation();

  const {
    originalDescription,
    classification,
    serviceId,
  } = location.state || {};

  // This is the description originally generated by the classifier.
  // We keep it unchanged so every refinement starts from the same base.
  const originalAiDescription =
    classification?.job_description ||
    originalDescription ||
    "";

  const [jobDescription, setJobDescription] =
    useState(originalAiDescription);

  const [additionalDetails, setAdditionalDetails] =
    useState("");

  const [lastRefinedDetails, setLastRefinedDetails] =
    useState("");

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");


  const handleUpdateDescription = async () => {
    const details = additionalDetails.trim();

    if (!details) {
      setError(
        "Please enter some additional information about the problem."
      );
      return;
    }

    setLoading(true);
    setError("");

    try {
      const result = await refineDescription(
        originalAiDescription,
        details
      );

      // Always use the description returned by the AI.
      // If the details were irrelevant, the Python service
      // returns the original description unchanged.
      setJobDescription(result.job_description);

      if (!result.is_relevant) {
        setError(
          "Please enter additional information that is relevant to the problem."
        );

        return;
      }

      // Remember exactly which additional details were
      // used to generate the current job description.
      setLastRefinedDetails(details);

    } catch (err) {
      console.error(err);

      setError(
        "Couldn't update the request description. Please try again."
      );

    } finally {
      setLoading(false);
    }
  };


  const handleFindProviders = async () => {
    setError("");

    const currentDetails = additionalDetails.trim();

    // If the user changed their additional details after
    // refining the description, make them update it again.
    if (
      currentDetails &&
      currentDetails !== lastRefinedDetails
    ) {
      setError(
        "Please update the request before continuing."
      );
      return;
    }

    setLoading(true);

    try {
      const finalClassification = {
        ...classification,

        additional_details:
          currentDetails || null,

        job_description:
          jobDescription,
      };

      const created = await createServiceRequest({
        description: jobDescription,

        location:
          getOnboarding().location || null,

        preferredDate: null,

        aiClassificationRaw:
          JSON.stringify(finalClassification),

        serviceId:
          serviceId ?? null,
      });

      // Continue using your existing classification/provider flow.
      navigate(
        `/requests/${created.id}/classification`,
        {
          state: {
            classification: finalClassification,
            serviceId:
              serviceId ?? null,
          },
        }
      );

    } catch (err) {
      console.error(err);

      setError(
        "Couldn't create the service request. Please try again."
      );

    } finally {
      setLoading(false);
    }
  };


  // If somebody manually visits /requests/review,
  // there won't be classification data in navigation state.
  if (!classification) {
    return (
      <Screen
        title="Review your request"
        subtitle="Check your request before continuing."
      >
        <ErrorBanner>
          We couldn't find the request information.
          Please go back and describe your problem again.
        </ErrorBanner>

        <Button
          onClick={() => navigate(-1)}
          className="mt-6"
        >
          Go back
        </Button>
      </Screen>
    );
  }


  return (
    <Screen
      title="Review your request"
      subtitle="Check the details and add anything else that may help the service provider."
    >

      {/* Service category */}
      <div className="mb-5">
        <p className="text-sm font-medium text-gray-500">
          Service
        </p>

        <p className="mt-1 capitalize text-gray-900">
          {classification.category}
        </p>
      </div>


      {/* Urgency */}
      <div className="mb-5">
        <p className="text-sm font-medium text-gray-500">
          Urgency
        </p>

        <p className="mt-1 capitalize text-gray-900">
          {classification.urgency}
        </p>
      </div>


      {/* Original customer message */}
      <div className="mb-5">
        <p className="text-sm font-medium text-gray-500">
          What you told us
        </p>

        <div className="mt-1 rounded-xl border border-gray-200 bg-white p-3 text-sm text-gray-900">
          {originalDescription}
        </div>
      </div>


      {/* AI-generated job description */}
      <div className="mb-5">
        <p className="text-sm font-medium text-gray-500">
          Job description
        </p>

        <div className="mt-1 rounded-xl border border-gray-200 bg-gray-50 p-3 text-sm text-gray-900">
          {jobDescription}
        </div>
      </div>


      {/* Additional information */}
      <div className="mb-4">
        <label
          htmlFor="additional-details"
          className="text-sm font-medium text-gray-700"
        >
          Additional details
        </label>

        <p className="mt-1 text-xs text-gray-500">
          Add anything else that could help the service
          provider better understand the problem.
        </p>

        <textarea
          id="additional-details"
          value={additionalDetails}
          onChange={(e) => {
            const value = e.target.value;

            setAdditionalDetails(value);
            setError("");

            if (!value.trim()) {
                setJobDescription(originalAiDescription);
                setLastRefinedDetails("");
            }
          }}
          placeholder="For example: The water is leaking underneath the sink and started this morning."
          className="mt-2 min-h-[110px] w-full rounded-xl border border-gray-200 bg-white p-3 text-sm focus:border-brand focus:outline-none focus:ring-1 focus:ring-brand"
        />
      </div>


      {/* Refine button */}
      <Button
        onClick={handleUpdateDescription}
        disabled={
          loading ||
          !additionalDetails.trim()
        }
      >
        {loading
          ? "Updating..."
          : "Update request"}
      </Button>


      {/* Error */}
      {error && (
        <div className="mt-4">
          <ErrorBanner>
            {error}
          </ErrorBanner>
        </div>
      )}


      {/* Loading */}
      {loading && (
        <div className="mt-4 rounded-lg border border-brand/30 bg-brand/5 px-3 py-2">
          <Loading label="🤖 Updating your request..." />
        </div>
      )}


      {/* Continue */}
      <Button
        onClick={handleFindProviders}
        disabled={loading}
        className="mt-6"
      >
        Find providers
      </Button>

    </Screen>
  );
}