import { createContext, useContext, useEffect, useMemo, useState } from "react";

const STORAGE_KEY = "ubuntulink.language";
const DEFAULT_LANGUAGE = "en";

export const LANGUAGES = [
  { code: "en", label: "English" },
  { code: "zu", label: "Zulu" },
  { code: "tn", label: "Setswana" },
  { code: "af", label: "Afrikaans" },
];

export const translations = {
  en: {
    "nav.home": "Home",
    "nav.requests": "Requests",
    "nav.profile": "Profile",
    "nav.dashboard": "Dashboard",
    "nav.bookings": "Bookings",
    "nav.logout": "Logout",
    "common.back": "Back",
    "welcome.title": "Local help. Right when you need it.",
    "welcome.subtitle": "Describe the problem. We identify the service and connect you with trusted local providers.",
    "welcome.primary": "Get started",
    "welcome.secondary": "Already have an account?",
    "welcome.login": "Log in",
    "welcome.tagline": "Find local skills. Compare confidently.",
    "login.title": "UbuntuLink",
    "login.subtitle": "Local help. Right when you need it.",
    "login.forgot": "Forgot password?",
    "login.noAccount": "No account?",
    "login.register": "Register",
    "login.signIn": "Sign in",
    "form.email": "Email",
    "form.password": "Password",
    "form.phone": "Phone number",
    "form.firstName": "First name",
    "form.lastName": "Last name",
    "form.name": "Your name",
    "form.location": "Location",
    "form.bio": "Bio",
    "form.whatMatters": "What matters most?",
    "action.continue": "Continue",
    "action.register": "Register",
    "action.signIn": "Sign in",
    "account.create": "Create your account",
    "provider.account": "I'm a service provider",
    "provider.setup": "Set up your provider profile",
    "provider.subtitle": "Customers will see this when they browse providers.",
    "provider.bioPlaceholder": "Tell customers about your experience...",
    "provider.locationPlaceholder": "Pretoria, Gauteng",
    "provider.optional": "A service you offer (optional, add more later)",
    "provider.choose": "Choose a service...",
    "provider.finish": "Finish setup",
    "provider.saving": "Saving...",
    "provider.openRequests": "Open requests",
    "provider.activeBookings": "Active bookings",
    "provider.browseRequests": "Browse service requests",
    "provider.findJobs": "Find jobs to quote on.",
    "provider.myBookings": "My bookings",
    "provider.profile": "Your profile",
    "provider.bio": "Bio",
    "provider.location": "Location",
    "provider.serviceRadius": "Service radius (km)",
    "provider.availableToday": "Available today",
    "provider.unavailableToday": "Unavailable today",
    "provider.saveProfile": "Save profile",
    "provider.yourServices": "Your services",
    "provider.noServices": "You haven't added any services yet.",
    "provider.remove": "Remove",
    "provider.addService": "Add a service",
    "provider.chooseService": "Choose a service...",
    "provider.minPrice": "Min price",
    "provider.maxPrice": "Max price",
    "customer.setup": "Let's get you set up",
    "customer.subtitle": "A few details help us find providers near you.",
    "customer.priority": "What matters most?",
    "customer.greetingMorning": "Good morning",
    "customer.greetingAfternoon": "Good afternoon",
    "customer.greetingEvening": "Good evening",
    "customer.helpTitle": "What do you need help with?",
    "customer.activeRequests": "Active requests",
    "customer.completedJobs": "Completed jobs",
    "customer.describe": "Describe your problem",
    "customer.describeSubtitle": "We'll help identify the right service.",
    "customer.findProvider": "Find a provider",
    "customer.askAi": "Ask AI",
    "customer.recent": "Recent requests",
    "customer.browse": "Browse by category",
    "customer.noRequests": "No requests yet — describe a problem to get started.",
    "customer.loadingServices": "Loading services...",
    "customer.noResults": "No providers matched that yet.",
    "customer.view": "View",
    "customer.problemTitle": "Describe your problem",
    "customer.problemSubtitle": "Tell us what's happening in your own words.",
    "customer.photoOptional": "Add a photo (optional)",
    "customer.readyAttach": "Ready to attach to this request",
    "customer.aiLoading": "🤖 Asking AI to read your problem and identify the right service...",
    "customer.aiLoadingShort": "Asking AI...",
    "customer.findRightService": "Find the right service",
    "customer.problemPreview": "My kitchen sink is leaking and I need someone to fix it today.",
    "customer.understandingTitle": "Understanding your request",
    "customer.understandingSubtitle": "🤖 UbuntuLink AI is identifying the service you need.",
    "customer.yourProblem": "Your problem",
    "customer.serviceIdentified": "Service identified",
    "customer.findingProviders": "Finding providers near you...",
    "customer.matchingInfo": "Matching on service, distance, price, ratings and availability.",
    "customer.providersFound": "providers found",
    "customer.providersLoading": "Finding providers...",
    "customer.providerAvailability": "Providers available near you",
    "customer.noServiceProviders": "No providers offer this service yet — check back soon.",
    "customer.compareProviders": "Compare providers",
    "customer.requestQuote": "Request a quote",
    "customer.quoteRequestSubtitle": "We'll flag your job to this provider.",
    "customer.providerTitle": "Provider",
    "customer.serviceTitle": "Service",
    "customer.expectedPrice": "Expected price range",
    "customer.sending": "Sending...",
    "customer.sendQuoteRequest": "Send quote request",
    "customer.quoteInfo": "Any provider can quote on this job — this just lets",
    "customer.quoteInfoTail": "know you're interested.",
    "customer.quotesReceived": "Quotes received",
    "customer.quotesReceivedSubtitle": "Providers who've responded to your job.",
    "customer.checkingQuotes": "Checking for quotes...",
    "customer.noQuotes": "No quotes yet — check back soon, or refresh this page.",
    "customer.accept": "Accept",
    "customer.decline": "Decline",
    "customer.reviewTitle": "Review provider",
    "customer.reviewSubtitle": "How was your experience?",
    "customer.thankYou": "Thank you!",
    "customer.reviewThanks": "Your review helps other customers find great providers.",
    "customer.backHome": "Back to home",
    "customer.submitReview": "Submit review",
    "customer.reviewPlaceholder": "Fast, professional and affordable.",
    "common.personFallback": "there",
    "common.language": "Language",
    "common.chooseLanguage": "Choose language",
    "common.readPage": "Read page",
    "common.stopReading": "Stop reading",
    "common.name": "Name",
    "common.location": "Location",
    "common.notSet": "Not set",
    "common.account": "Account",
    "common.signOut": "Sign out",
    "common.signIn": "Sign in",
    "common.notSignedIn": "Not signed in",
    "common.serviceRequest": "Service request",
    "common.provider": "Provider",
    "common.service": "Service",
    "common.remove": "Remove",
    "common.readyAttach": "Ready to attach to this request",
    "common.skip": "Skip",
    "common.availableToday": "Available today",
    "common.unavailableToday": "Unavailable today",
    "common.noReviews": "No reviews yet.",
    "common.requestQuote": "Request a quote",
    "common.aboutProvider": "About this provider",
    "common.recentReviews": "Recent reviews",
    "common.startFromProblem": "Start from \"Describe your problem\" to request a quote.",
    "common.accept": "Accept",
    "common.decline": "Decline",
    "common.submit": "Submit",
    "common.loading": "Loading...",
    "common.yes": "Yes",
    "common.no": "No",
  },
  zu: {
    "nav.home": "Ekhaya",
    "nav.requests": "Izicelo",
    "nav.profile": "Iphrofayili",
    "nav.dashboard": "Idashboard",
    "nav.bookings": "Amabookings",
    "nav.logout": "Phuma",
    "common.back": "Emuva",
    "welcome.title": "Usizo lwendawo. Ngesikhathi esifanele.",
    "welcome.subtitle": "Chaza inkinga. Sizobona isevisi bese sikhona nabahlinzeki bendawo abathembekile.",
    "welcome.primary": "Qala",
    "welcome.secondary": "Usuvele une-account?",
    "welcome.login": "Ngena",
    "welcome.tagline": "Thola amakhono endawo. Qhathanisa ngokuzethemba.",
    "login.title": "UbuntuLink",
    "login.subtitle": "Usizo lwendawo. Ngesikhathi esifanele.",
    "login.forgot": "Ukhohlwe iphasiwedi?",
    "login.noAccount": "Ayikho i-account?",
    "login.register": "Bhalisa",
    "login.signIn": "Ngena",
    "form.email": "I-imeyili",
    "form.password": "Iphasiwedi",
    "form.phone": "Inombolo yefoni",
    "form.firstName": "Igama lokuqala",
    "form.lastName": "Igama lokugcina",
    "form.name": "Igama lakho",
    "form.location": "Indawo",
    "form.bio": "I-bio",
    "form.whatMatters": "Yini ebalulekile kuwe?",
    "action.continue": "Qhubeka",
    "action.register": "Bhalisa",
    "action.signIn": "Ngena",
    "account.create": "Dala i-account yakho",
    "provider.account": "Ngingumhlinzeki wesevisi",
    "provider.setup": "Setha iphrofayili yakho yomhlinzeki",
    "provider.subtitle": "Abathengi bazobona lokhu lapho bebheka abahlinzeki.",
    "provider.bioPlaceholder": "Tshela abathengi ngolwazi lwakho...",
    "provider.locationPlaceholder": "Pretoria, Gauteng",
    "provider.optional": "Isevisi oyihlinzekayo (kungakhetha, ungeze kamuva)",
    "provider.choose": "Khetha isevisi...",
    "provider.finish": "Qeda usethe",
    "provider.saving": "Kuyagcinwa...",
    "provider.openRequests": "Izicelo ezivulekile",
    "provider.activeBookings": "Amabookings asebenzayo",
    "provider.browseRequests": "Bheka izicelo zezinkonzo",
    "provider.findJobs": "Thola imisebenzi yokubiza quote.",
    "provider.myBookings": "Amabookings ami",
    "provider.profile": "Iphrofayili yakho",
    "provider.bio": "I-bio",
    "provider.location": "Indawo",
    "provider.serviceRadius": "Ibanga lesevisi (km)",
    "provider.availableToday": "Iyatholakala namuhla",
    "provider.unavailableToday": "Ayitholakali namuhla",
    "provider.saveProfile": "Gcina iphrofayili",
    "provider.yourServices": "Amasevisi akho",
    "provider.noServices": "Awukaze ufake amasevisi.",
    "provider.remove": "Susa",
    "provider.addService": "Engeza isevisi",
    "provider.chooseService": "Khetha isevisi...",
    "provider.minPrice": "Intengo ephansi",
    "provider.maxPrice": "Intengo ephezulu",
    "customer.setup": "Masikusetheleni",
    "customer.subtitle": "Imininingwane embalwa isiza ukuthola abahlinzeki endaweni.",
    "customer.priority": "Yini ebalulekile kuwe?",
    "customer.greetingMorning": "Sawubona",
    "customer.greetingAfternoon": "Sawubona",
    "customer.greetingEvening": "Sawubona",
    "customer.helpTitle": "Yini oyidingayo?",
    "customer.activeRequests": "Izicelo ezisebenzayo",
    "customer.completedJobs": "Imisebenzi ephelile",
    "customer.describe": "Chaza inkinga yakho",
    "customer.describeSubtitle": "Sizokusiza ukuthola isevisi efanele.",
    "customer.findProvider": "Thola umhlinzeki",
    "customer.askAi": "Buza i-AI",
    "customer.recent": "Izicelo ezedlule",
    "customer.browse": "Dlulisa ngobuningi",
    "customer.noRequests": "Awekho ama-request okwamanje — chaza inkinga ukuze uqale.",
    "customer.loadingServices": "Kulayishwa izinsizakalo...",
    "customer.noResults": "Awekho abahlinzeki abahambisanayo okwamanje.",
    "customer.view": "Buka",
    "customer.problemTitle": "Chaza inkinga yakho",
    "customer.problemSubtitle": "Sitshele ukuthi kwenzakalani ngokwami amazwi akho.",
    "customer.photoOptional": "Engeza isithombe (ongakukhetha)",
    "customer.readyAttach": "Ilungile ukunikwe kulokhu kucela",
    "customer.aiLoading": "🤖 I-AI iyafunda inkinga yakho ukuze ibone isevisi efanele...",
    "customer.aiLoadingShort": "I-AI iyasebenza...",
    "customer.findRightService": "Thola isevisi efanele",
    "customer.problemPreview": "Umthombo wami we-kitchen uyadabuka futhi ngidinga umuntu ozowuqinisekisa namuhla.",
    "customer.understandingTitle": "Siyaqonda isicelo sakho",
    "customer.understandingSubtitle": "🤖 I-UbuntuLink AI ibona isevisi oyidingayo.",
    "customer.yourProblem": "Inkinga yakho",
    "customer.serviceIdentified": "Isevisi itholiwe",
    "customer.findingProviders": "Sithola abahlinzeki endaweni...",
    "customer.matchingInfo": "Kufaniswa isevisi, ibanga, intengo, izilinganiso nokutholakala.",
    "customer.providersFound": "abahlinzeki abatholiwe",
    "customer.providersLoading": "Kuyatholwa abahlinzeki...",
    "customer.providerAvailability": "Abahlinzeki abatholakalayo endaweni",
    "customer.noServiceProviders": "Awekho abahlinzeki bale sevisi okwamanje — buyela emuva maduzane.",
    "customer.compareProviders": "Qhathanisa abahlinzeki",
    "customer.requestQuote": "Cela i-quote",
    "customer.quoteRequestSubtitle": "Sizobeka umsebenzi wakho kulo mhlinzeki.",
    "customer.providerTitle": "Umhlinzeki",
    "customer.serviceTitle": "Isevisi",
    "customer.expectedPrice": "Intengo elindelekile",
    "customer.sending": "Kuyathunyelwa...",
    "customer.sendQuoteRequest": "Thumela isicelo se-quote",
    "customer.quoteInfo": "Noma yimuphi umhlinzeki angathumela i-quote — lokhu kukhombisa ukuthi",
    "customer.quoteInfoTail": "ufuna ukuba akuthinte.",
    "customer.quotesReceived": "Ama-quote atholiwe",
    "customer.quotesReceivedSubtitle": "Abahlinzeki abasiphendule emsebenzini wakho.",
    "customer.checkingQuotes": "Kuyahlolwa ama-quote...",
    "customer.noQuotes": "Awekho ama-quote okwamanje — buyela emuva kancane, noma uvuselele leli khasi.",
    "customer.accept": "Yamukela",
    "customer.decline": "Yenqaba",
    "customer.reviewTitle": "Hlola umhlinzeki",
    "customer.reviewSubtitle": "Uzwile kanjani ulwazi lwakho?",
    "customer.thankYou": "Siyabonga!",
    "customer.reviewThanks": "Ukubuyekeza kwakho kusiza abanye abathengi ukuthola abahlinzeki abahle.",
    "customer.backHome": "Buyela ekhaya",
    "customer.submitReview": "Thumela ukubuyekeza",
    "customer.reviewPlaceholder": "Isheshile, professional, futhi iyafanele.",
    "common.personFallback": "lapho",
    "common.language": "Ulimi",
    "common.chooseLanguage": "Khetha ulimi",
    "common.readPage": "Funda ikhasi",
    "common.stopReading": "Misa ukufunda",
    "common.name": "Igama",
    "common.location": "Indawo",
    "common.notSet": "Akusethiwe",
    "common.account": "I-account",
    "common.signOut": "Phuma",
    "common.signIn": "Ngena",
    "common.notSignedIn": "Akungenanga",
    "common.serviceRequest": "Isicelo sesevisi",
    "common.provider": "Umhlinzeki",
    "common.service": "Isevisi",
    "common.remove": "Susa",
    "common.readyAttach": "Ilungile ukunikwe kulokhu kucela",
    "common.skip": "Yeqa",
    "common.availableToday": "Iyatholakala namuhla",
    "common.unavailableToday": "Ayitholakali namuhla",
    "common.noReviews": "Awekho ukubuyekezwa okwamanje.",
    "common.requestQuote": "Cela i-quote",
    "common.aboutProvider": "Mayelana nomhlinzeki",
    "common.recentReviews": "Ukubuyekezwa kwakamuva",
    "common.startFromProblem": "Qala ku-\"Chaza inkinga yakho\" ukuze ucele i-quote.",
    "common.accept": "Yamukela",
    "common.decline": "Yenqaba",
    "common.submit": "Thumela",
    "common.loading": "Kuyalayishwa...",
    "common.yes": "Yebo",
    "common.no": "Cha",
  },
  tn: {
    "nav.home": "Lapeng",
    "nav.requests": "Dikopo",
    "nav.profile": "Porofeile",
    "nav.dashboard": "Dashboard",
    "nav.bookings": "Dipene",
    "nav.logout": "Tlogela",
    "common.back": "Morago",
    "welcome.title": "Thušo ya mo gae. Ka nako e e nepagetseng.",
    "welcome.subtitle": "Tlhalosa bothata. Re lemoga tirelo mme re go golaganya le bafani ba maemo ba ba tshepagalang.",
    "welcome.primary": "Simolola",
    "welcome.secondary": "A o setse o na le akhaonte?",
    "welcome.login": "Tsena",
    "welcome.tagline": "Fumana dikgomo tsa lehae. Tlhahloba ka boitshepo.",
    "login.title": "UbuntuLink",
    "login.subtitle": "Thušo ya mo gae. Ka nako e e nepagetseng.",
    "login.forgot": "O lebetse password?",
    "login.noAccount": "A o sena akhaonte?",
    "login.register": "Ingodise",
    "login.signIn": "Tsena",
    "form.email": "E-mail",
    "form.password": "Password",
    "form.phone": "Nomoro ya mogala",
    "form.firstName": "Leina la ntlha",
    "form.lastName": "Leina la bofelo",
    "form.name": "Leina la gago",
    "form.location": "Boagi",
    "form.bio": "Bio",
    "form.whatMatters": "Ke eng se se botlhokwa go wena?",
    "action.continue": "Tswela pele",
    "action.register": "Ingodise",
    "action.signIn": "Tsena",
    "account.create": "Bula akhaonte ya gago",
    "provider.account": "Ke mofani wa tirelo",
    "provider.setup": "Sethup porofeile ya gago",
    "provider.subtitle": "Bateratari ba tla e bona fa ba batla bafani.",
    "provider.bioPlaceholder": "Bolelela bareki ka bokgoni jwa gago...",
    "provider.locationPlaceholder": "Pretoria, Gauteng",
    "provider.optional": "Tirelo eo o e fang (ka go ikgethela, o ka e oketsa morago)",
    "provider.choose": "Kgetha tirelo...",
    "provider.finish": "Fetsa setup",
    "provider.saving": "E a boloka...",
    "provider.openRequests": "Dikopo tse di bulegilweng",
    "provider.activeBookings": "Dipene tse di dirang",
    "provider.browseRequests": "Batlisisa dikopo tsa tirelo",
    "provider.findJobs": "Fumana ditiro tsa quote.",
    "provider.myBookings": "Dipene tsa me",
    "provider.profile": "Porofeile ya gago",
    "provider.bio": "Bio",
    "provider.location": "Boagi",
    "provider.serviceRadius": "Boleele jwa tirelo (km)",
    "provider.availableToday": "E a bereka gompieno",
    "provider.unavailableToday": "Ga e a bereka gompieno",
    "provider.saveProfile": "Boloka porofeile",
    "provider.yourServices": "Ditirelo tsa gago",
    "provider.noServices": "Ga o ise o tsenye ditirelo.",
    "provider.remove": "Tlosa",
    "provider.addService": "Oketsa tirelo",
    "provider.chooseService": "Kgetha tirelo...",
    "provider.minPrice": "Theko e e kwa tlase",
    "provider.maxPrice": "Theko e e kwa godimo",
    "customer.setup": "A re go tlhame",
    "customer.subtitle": "Lintlha tse nnye di re thusa go fumana bafani ba mo gae.",
    "customer.priority": "Ke eng se se botlhokwa go wena?",
    "customer.greetingMorning": "Dumela",
    "customer.greetingAfternoon": "Dumela",
    "customer.greetingEvening": "Dumela",
    "customer.helpTitle": "Ke eng se o se tlhokang?",
    "customer.activeRequests": "Dikopo tse di dirang",
    "customer.completedJobs": "Diro tse di fetsweng",
    "customer.describe": "Tlhalosa bothata jwa gago",
    "customer.describeSubtitle": "Re tla go thusa go bona tirelo e e nepagetseng.",
    "customer.findProvider": "Fumana mofani",
    "customer.askAi": "Botsa AI",
    "customer.recent": "Dikopo tse di sa tswa",
    "customer.browse": "Bona ka setlhopha",
    "customer.noRequests": "Ga go na dikopo - tlhalosa bothata go simolola.",
    "customer.loadingServices": "Ditetse tsa go tshegetsa di a laisiwa...",
    "customer.noResults": "Ga go na bafani ba ba tsamaisanang le seo.",
    "customer.view": "Bona",
    "customer.problemTitle": "Tlhalosa bothata jwa gago",
    "customer.problemSubtitle": "Re bolelle se se diragalang ka mafoko a gago.",
    "customer.photoOptional": "Oketsa setshwantsho (ga se boseyane)",
    "customer.readyAttach": "Se ikemetse go neelwa mo kopong e.",
    "customer.aiLoading": "🤖 AI e bala bothata jwa gago e lebelela tirelo e e nepagetseng...",
    "customer.aiLoadingShort": "AI e a dira...",
    "customer.findRightService": "Fumana tirelo e e nepagetseng",
    "customer.problemPreview": "Sekhukhune sa ka sa kitchen se a dutla mme ke tlhoka motho yo o ka se rregisang gompieno.",
    "customer.understandingTitle": "Re tlhaloganya kopo ya gago",
    "customer.understandingSubtitle": "🤖 UbuntuLink AI e lemoga tirelo e o e tlhokang.",
    "customer.yourProblem": "Bothata jwa gago",
    "customer.serviceIdentified": "Tirelo e lemogilwe",
    "customer.findingProviders": "Re batla bafani mo tikologong...",
    "customer.matchingInfo": "Re bapisa tirelo, sebaka, theko, dikadiso le boteng.",
    "customer.providersFound": "bafani ba ba bonweng",
    "customer.providersLoading": "Re batla bafani...",
    "customer.providerAvailability": "Bafani ba ba teng mo tikologong",
    "customer.noServiceProviders": "Ga go na bafani ba tirelo e - batla gape mo nakong e e tlang.",
    "customer.compareProviders": "Bapisa bafani",
    "customer.requestQuote": "Kopa quote",
    "customer.quoteRequestSubtitle": "Re tla tsenya tiro ya gago mo mofaning yo.",
    "customer.providerTitle": "Mofani",
    "customer.serviceTitle": "Tirelo",
    "customer.expectedPrice": "Theko e e solofetsweng",
    "customer.sending": "E a romelwa...",
    "customer.sendQuoteRequest": "Romela kopo ya quote",
    "customer.quoteInfo": "Mofani mongwe le mongwe a ka romela quote - seno se re bolelela fela gore",
    "customer.quoteInfoTail": "o a rata.",
    "customer.quotesReceived": "Diquote tse di amogetsweng",
    "customer.quotesReceivedSubtitle": "Bafani ba ba arabelang tiro ya gago.",
    "customer.checkingQuotes": "Go tlhotlhoba diquote...",
    "customer.noQuotes": "Ga go na diquote - batla gape, kgotsa refresh this page.",
    "customer.accept": "Amogela",
    "customer.decline": "Nkana",
    "customer.reviewTitle": "Tlhatlhoba mofani",
    "customer.reviewSubtitle": "U itemogetse jang?",
    "customer.thankYou": "Ke a leboga!",
    "customer.reviewThanks": "Tlhahlobo ya gago e thusa bareki ba bangwe go bona bafani ba ba botoka.",
    "customer.backHome": "Boela lapeng",
    "customer.submitReview": "Romela tlhahlobo",
    "customer.reviewPlaceholder": "E potlakile, e kgethegile, e theko e botoka.",
    "common.personFallback": "gape",
    "common.language": "Puo",
    "common.chooseLanguage": "Kgetha puo",
    "common.readPage": "Buisa leqephe",
    "common.stopReading": "Emisa go buisa",
    "common.name": "Leina",
    "common.location": "Boagi",
    "common.notSet": "Ga se se setseng",
    "common.account": "Akhawunti",
    "common.signOut": "Tlogela",
    "common.signIn": "Tsena",
    "common.notSignedIn": "Ga o tsene",
    "common.serviceRequest": "Kopo ya tirelo",
    "common.provider": "Mofani",
    "common.service": "Tirelo",
    "common.remove": "Tlosa",
    "common.readyAttach": "Se ikemetse go neelwa mo kopong e.",
    "common.skip": "Tsamaya",
    "common.availableToday": "E a bereka gompieno",
    "common.unavailableToday": "Ga e a bereka gompieno",
    "common.noReviews": "Ga go na ditlhahlobo.",
    "common.requestQuote": "Kopa quote",
    "common.aboutProvider": "Ka mofani",
    "common.recentReviews": "Ditlhahlobo tsa gompieno",
    "common.startFromProblem": "Simolola ka \"Tlhalosa bothata jwa gago\" go kopa quote.",
    "common.accept": "Amogela",
    "common.decline": "Nkana",
    "common.submit": "Romela",
    "common.loading": "E a laisiwa...",
    "common.yes": "Ee",
    "common.no": "Nnyaa",
  },
  af: {
    "nav.home": "Tuis",
    "nav.requests": "Versoeke",
    "nav.profile": "Profiel",
    "nav.dashboard": "Paneel",
    "nav.bookings": "Besprekings",
    "nav.logout": "Meld af",
    "common.back": "Terug",
    "welcome.title": "Plaaslike hulp. Presies wanneer jy dit nodig het.",
    "welcome.subtitle": "Beskryf die probleem. Ons identifiseer die diens en verbind jou met betroubare plaaslike verskaffers.",
    "welcome.primary": "Begin",
    "welcome.secondary": "Reeds 'n rekening?",
    "welcome.login": "Teken in",
    "welcome.tagline": "Vind plaaslike vaardighede. Vergelyk selfversekerd.",
    "login.title": "UbuntuLink",
    "login.subtitle": "Plaaslike hulp. Presies wanneer jy dit nodig het.",
    "login.forgot": "Wagwoord vergeet?",
    "login.noAccount": "Geen rekening?",
    "login.register": "Registreer",
    "login.signIn": "Teken in",
    "form.email": "E-pos",
    "form.password": "Wagwoord",
    "form.phone": "Selfoonnommer",
    "form.firstName": "Voornaam",
    "form.lastName": "Van",
    "form.name": "Jou naam",
    "form.location": "Ligging",
    "form.bio": "Bio",
    "form.whatMatters": "Wat is vir jou die belangrikste?",
    "action.continue": "Gaan voort",
    "action.register": "Registreer",
    "action.signIn": "Teken in",
    "account.create": "Skep jou rekening",
    "provider.account": "Ek is 'n diensverskaffer",
    "provider.setup": "Stel jou diensverskafferprofiel op",
    "provider.subtitle": "Kliënte sal dit sien wanneer hulle verskaffers blaai.",
    "provider.bioPlaceholder": "Vertel kliënte van jou ervaring...",
    "provider.locationPlaceholder": "Pretoria, Gauteng",
    "provider.optional": "'n Diens wat jy aanbied (opsioneel, voeg later meer by)",
    "provider.choose": "Kies 'n diens...",
    "provider.finish": "Voltooi opstelling",
    "provider.saving": "Besig om te stoor...",
    "provider.openRequests": "Oop versoeke",
    "provider.activeBookings": "Aktiewe besprekings",
    "provider.browseRequests": "Blader deur diensversoeke",
    "provider.findJobs": "Vind werk om te kwoteer.",
    "provider.myBookings": "My besprekings",
    "provider.profile": "Jou profiel",
    "provider.bio": "Bio",
    "provider.location": "Ligging",
    "provider.serviceRadius": "Diensradius (km)",
    "provider.availableToday": "Vandag beskikbaar",
    "provider.unavailableToday": "Vandag nie beskikbaar nie",
    "provider.saveProfile": "Stoor profiel",
    "provider.yourServices": "Jou dienste",
    "provider.noServices": "Jy het nog geen dienste bygevoeg nie.",
    "provider.remove": "Verwyder",
    "provider.addService": "Voeg 'n diens by",
    "provider.chooseService": "Kies 'n diens...",
    "provider.minPrice": "Minimum prys",
    "provider.maxPrice": "Maksimum prys",
    "customer.setup": "Kom ons stel jou op",
    "customer.subtitle": "'n Paar inligting help ons om verskaffers naby jou te vind.",
    "customer.priority": "Wat is vir jou die belangrikste?",
    "customer.greetingMorning": "Goeiemôre",
    "customer.greetingAfternoon": "Goeiemiddag",
    "customer.greetingEvening": "Goeienaand",
    "customer.helpTitle": "Waarmee help jy nodig?",
    "customer.activeRequests": "Aktiewe versoeke",
    "customer.completedJobs": "Voltooide werk",
    "customer.describe": "Beskryf jou probleem",
    "customer.describeSubtitle": "Ons help jou om die regte diens te vind.",
    "customer.findProvider": "Vind 'n verskaffer",
    "customer.askAi": "Vra AI",
    "customer.recent": "Onlangse versoeke",
    "customer.browse": "Blader per kategorie",
    "customer.noRequests": "Nog geen versoeke nie — beskryf 'n probleem om te begin.",
    "customer.loadingServices": "Laai dienste...",
    "customer.noResults": "Geen verskaffers het nog ooreengestem nie.",
    "customer.view": "Bekyk",
    "customer.problemTitle": "Beskryf jou probleem",
    "customer.problemSubtitle": "Vertel ons in jou eie woorde wat gebeur.",
    "customer.photoOptional": "Voeg 'n foto by (opsioneel)",
    "customer.readyAttach": "Gereed om aan hierdie versoek te heg",
    "customer.aiLoading": "🤖 AI lees jou probleem en bepaal die regte diens...",
    "customer.aiLoadingShort": "AI werk tans...",
    "customer.findRightService": "Vind die regte diens",
    "customer.problemPreview": "My kombuiskraan lek en ek het vandag iemand nodig om dit reg te maak.",
    "customer.understandingTitle": "Ons verstaan jou versoek",
    "customer.understandingSubtitle": "🤖 UbuntuLink AI identifiseer die diens wat jy nodig het.",
    "customer.yourProblem": "Jou probleem",
    "customer.serviceIdentified": "Diens geïdentifiseer",
    "customer.findingProviders": "Soek verskaffers naby jou...",
    "customer.matchingInfo": "Soek volgens diens, afstand, prys, beoordeling en beskikbaarheid.",
    "customer.providersFound": "verskaffers gevind",
    "customer.providersLoading": "Soek verskaffers...",
    "customer.providerAvailability": "Verskaffers beskikbaar naby jou",
    "customer.noServiceProviders": "Geen verskaffer bied hierdie diens nog aan nie — kom later weer kyk.",
    "customer.compareProviders": "Vergelyk verskaffers",
    "customer.requestQuote": "Vra vir 'n kwotasie",
    "customer.quoteRequestSubtitle": "Ons sal jou werk aan hierdie verskaffer merk.",
    "customer.providerTitle": "Verskaffer",
    "customer.serviceTitle": "Diens",
    "customer.expectedPrice": "Verwagte prysreeks",
    "customer.sending": "Besig om te stuur...",
    "customer.sendQuoteRequest": "Stuur kwotasieversoek",
    "customer.quoteInfo": "Enige verskaffer kan op hierdie werk kwoteer — dit wys net dat",
    "customer.quoteInfoTail": "belangstel.",
    "customer.quotesReceived": "Kwotasies ontvang",
    "customer.quotesReceivedSubtitle": "Verskaffers wat op jou werk gereageer het.",
    "customer.checkingQuotes": "Kontroleer kwotasies...",
    "customer.noQuotes": "Nog geen kwotasies nie — kom later weer kyk of herlaai hierdie bladsy.",
    "customer.accept": "Aanvaar",
    "customer.decline": "Weier",
    "customer.reviewTitle": "Resenseer verskaffer",
    "customer.reviewSubtitle": "Hoe was jou ervaring?",
    "customer.thankYou": "Dankie!",
    "customer.reviewThanks": "Jou resensie help ander kliënte om goeie verskaffers te vind.",
    "customer.backHome": "Terug na tuis",
    "customer.submitReview": "Dien resensie in",
    "customer.reviewPlaceholder": "Vinnig, professioneel en bekostigbaar.",
    "common.personFallback": "daar",
    "common.language": "Taal",
    "common.chooseLanguage": "Kies taal",
    "common.readPage": "Lees bladsy",
    "common.stopReading": "Stop lees",
    "common.name": "Naam",
    "common.location": "Ligging",
    "common.notSet": "Nie ingestel nie",
    "common.account": "Rekening",
    "common.signOut": "Meld af",
    "common.signIn": "Teken in",
    "common.notSignedIn": "Nie aangemeld nie",
    "common.serviceRequest": "Diensversoek",
    "common.provider": "Verskaffer",
    "common.service": "Diens",
    "common.remove": "Verwyder",
    "common.readyAttach": "Gereed om aan hierdie versoek te heg",
    "common.skip": "Slaan oor",
    "common.availableToday": "Vandag beskikbaar",
    "common.unavailableToday": "Vandag nie beskikbaar nie",
    "common.noReviews": "Nog geen resensies nie.",
    "common.requestQuote": "Vra vir 'n kwotasie",
    "common.aboutProvider": "Oor hierdie verskaffer",
    "common.recentReviews": "Onlangse resensies",
    "common.startFromProblem": "Begin by \"Beskryf jou probleem\" om 'n kwotasie te vra.",
    "common.accept": "Aanvaar",
    "common.decline": "Weier",
    "common.submit": "Dien in",
    "common.loading": "Laai...",
    "common.yes": "Ja",
    "common.no": "Nee",
  }
};

export function getStoredLanguage() {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    return stored && translations[stored] ? stored : DEFAULT_LANGUAGE;
  } catch {
    return DEFAULT_LANGUAGE;
  }
}

const LanguageContext = createContext({
  language: DEFAULT_LANGUAGE,
  setLanguage: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(getStoredLanguage);

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
  }, [language]);

  const t = (key) => translations[language]?.[key] || translations.en[key] || key;

  const value = useMemo(() => ({ language, setLanguage, t }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
