# Allow .env to be access in properties
spring.config.import=file:./backend/.env[.properties]

spring.application.name=backend
spring.datasource.url=${SUPABASE_DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

#spring.security.user.name=myuser
#spring.security.user.password=mypassword